services:
  - type: web
    name: ecommerce-platform
    env: node
    plan: free
    buildCommand: npm ci && npm --prefix client ci && npm --prefix client run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://ecommerce-platform.onrender.com
      - key: JWT_SECRET
        generateValue: true

